---
title: "Floodplain_plots"
author: "Tingrui Huang"
date: "April 27, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library
```{r }
library(tidyverse)
library(plotly)
```

# Data
```{r }
dfi <- read.csv("all_borough_v2.csv")
```

# Floodplain - Number of buildings
```{r }
# Bronx and Manhattan
  BM_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(BM_bldg)
  
# Bronx and Brooklyn
    BB_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Brooklyn")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(BB_bldg)
  
# Bronx and Queens
  BQ_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(BQ_bldg)
  
# Bronx and Staten Island
  BSI_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(BSI_bldg)
  
# Brooklyn and Queens
  BklQ_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(BklQ_bldg)
  
# Brooklyn and Manhattan
  BklM_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(BklM_bldg)
  
# Brooklyn and Staten Island
  BklSI_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(BklSI_bldg)
  
# Manhattan and Queens
  ManQ_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(ManQ_bldg)
  
# Manhattan and Staten Island
  ManSI_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(ManSI_bldg)
  
# Queens and Staten Island
  QSI_bldg <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Queens" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_bldg, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Buildings are in the 1% Annual Chance floodplain")
  ggplotly(QSI_bldg)
```

# Floodplain - Number of residential housing units
```{r }
# Bronx and Manhattan
  BM_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(BM_units)
  
# Bronx and Brooklyn
    BB_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Brooklyn")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(BB_units)
  
# Bronx and Queens
  BQ_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(BQ_units)
  
# Bronx and Staten Island
  BSI_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(BSI_units)
  
# Brooklyn and Queens
  BklQ <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(BklQ)
  
# Brooklyn and Manhattan
  BklM_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(BklM_units)
  
# Brooklyn and Staten Island
  BklSI_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(BklSI_units)
  
# Manhattan and Queens
  ManQ_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(ManQ_units)
  
# Manhattan and Staten Island
  ManSI_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(ManSI_units)
  
# Queens and Staten Island
  QSI_units <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Queens" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_resunits, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge())+
        ggtitle("Residential Housing Units are in the 1% Annual Chance floodplain")
  ggplotly(QSI_units)
```

# Floodplain - Lot area
```{r }
# Bronx and Manhattan
  BM_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(BM_area)
  
# Bronx and Brooklyn
    BB_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Brooklyn")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(BB_area)
  
# Bronx and Queens
  BQ_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(BQ_area)
  
# Bronx and Staten Island
  BSI_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(BSI_area)
  
# Brooklyn and Queens
  BklQ_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(BklQ_area)
  
# Brooklyn and Manhattan
  BklM_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(BklM_area)
  
# Brooklyn and Staten Island
  BklSI_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(BklSI_area)
  
# Manhattan and Queens
  ManQ_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(ManQ_area)
  
# Manhattan and Staten Island
  ManSI_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(ManSI_area)
  
# Queens and Staten Island
  QSI_area <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Queens" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_area, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Lot Area are in the 1% Annual Chance floodplain")
  ggplotly(QSI_area)
```

# Floodplain - Open space
```{r }
# Bronx and Manhattan
  BM_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(BM_open)
  
# Bronx and Brooklyn
    BB_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Brooklyn")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(BB_open)
  
# Bronx and Queens
  BQ_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(BQ_open)
  
# Bronx and Staten Island
  BSI_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Bronx" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(BSI_open)
  
# Brooklyn and Queens
  BklQ_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(BklQ_open)
  
# Brooklyn and Manhattan
  BklM_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Manhattan")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(BklM_open)
  
# Brooklyn and Staten Island
  BklSI_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Brooklyn" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(BklSI_open)
  
# Manhattan and Queens
  ManQ_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Queens")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(ManQ_open)
  
# Manhattan and Staten Island
  ManSI_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Manhattan" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(ManSI_open)
  
# Queens and Staten Island
  QSI_open <- dfi%>%
        group_by(borough)%>%
        filter(borough == "Queens" | borough == "Staten Island")%>%
        ggplot(aes(x=borough, y=fp_500_openspace, fill=subborough)) +
        geom_bar(stat="identity", position=position_dodge()) +
        ggtitle("Total Open Space are in the 1% Annual Chance floodplain")
  ggplotly(QSI_open)
```