---
title: "Data"
author: "Mark"
date: "4/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(httr)
library(corrplot)
library(ggplot2)
library(httr)
library(rgdal)
library(broom)
library(plotly)
library(readr)
library(rgeos)
library(leaflet)
library(ggmap)
library(varhandle)
library(miceadds)
library(tigris)
```


```{r}
map_data_nyc <- read.csv("map_data.csv")

 r <- GET("http://data.beta.nyc//dataset/472dda10-79b3-4bfb-9c75-e7bd5332ec0b/resource/d826bbc6-a376-4642-8d8b-3a700d701557/download/88472a1f6fd94fef97b8c06335db60f7nyccommunitydistricts.geojson")
# # 
nycounties <- readOGR(content(r, "text"), "OGRGeoJSON", verbose = F)
# # 
nycounties <- geojsonio::geojson_read("Community Districts.geojson",
  what = "sp")
# Or use the rgdal equivalent:
# nycounties <- rgdal::readOGR("json/nycounties.geojson", "OGRGeoJSON")

map_data <- geo_join(nycounties, map_data_nyc, "communityDistrict", "borocd",how="inner")
pal <- colorNumeric("viridis", NULL)


A <- as.character("pop_2010")

leaflet(map_data) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.9,
    fillColor = ~pal(log10(map_data[[A]])),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE),
    label = ~paste0(CD.Name, ": ", formatC(map_data[[A]], big.mark = ","))) %>%
  addLegend(pal = pal, values = ~log10(map_data[[A]]), opacity = 1.0,
    labFormat = labelFormat(transform = function(x) round(10^x)))





```